# Generated by Django 4.1.1 on 2022-12-31 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LieuDeNaissance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_lieu_de_naissance', models.CharField(choices=[['Hopital', 'H'], ['Centre de santé', 'CDS'], ['À Domicile', 'D']], max_length=30)),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('commune', models.CharField(max_length=200)),
                ('province', models.CharField(max_length=200)),
                ('pays', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Umurundi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('prenom', models.CharField(max_length=200)),
                ('sexe', models.CharField(choices=[['Masculin', 'M'], ['Feminin', 'F']], max_length=10)),
                ('date_naissance', models.DateTimeField()),
                ('cni_pere', models.CharField(max_length=30, unique=True)),
                ('cni_mere', models.CharField(max_length=30, unique=True)),
                ('lieu_de_naissance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.lieudenaissance')),
            ],
        ),
    ]
