# Generated by Django 4.1.1 on 2022-12-31 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admnistrateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[['IT Manager', 'IT Manager'], ['IT Technician', 'IT Technician'], ['Chef de zone', 'Chef de zone']], max_length=60)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
        migrations.CreateModel(
            name='LieuDeNaissance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_lieu_de_naissance', models.CharField(choices=[['Hopital', 'Hopital'], ['Centre de santé', 'Centre de santé'], ['À Domicile', 'À Domicile']], max_length=30)),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('commune', models.CharField(max_length=200)),
                ('province', models.CharField(max_length=200)),
                ('pays', models.CharField(max_length=100)),
                ('admnistrateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.admnistrateur')),
            ],
        ),
        migrations.CreateModel(
            name='Umurundi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('prenom', models.CharField(max_length=200)),
                ('sexe', models.CharField(choices=[['Masculin', 'Masculin'], ['Feminin', 'Feminin']], max_length=10)),
                ('date_naissance', models.DateTimeField()),
                ('cni_pere', models.CharField(max_length=30, unique=True)),
                ('cni_mere', models.CharField(max_length=30, unique=True)),
                ('admnistrateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.admnistrateur')),
                ('lieu_de_naissance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.lieudenaissance')),
            ],
        ),
    ]
